#!/usr/bin/env python3
"""Generate ``application/country_boxes.py`` from Natural Earth 1:10m data.

The saved-places menu wants a bounding box and a continent for every country.
Typing ~195 of each by hand invites transcription errors; reading them from the
1:10m ``admin_0_countries`` shapefile (public domain) does not.

Two classes of country need a curated box rather than the raw geometry bounds:

* **Antimeridian spanners** (Russia, the United States, Fiji, New Zealand,
  Kiribati). Their geometry crosses 180 degrees, so the raw longitude bounds run
  the whole -180..180 width and would frame the entire world.
* **Distant territories** (France's Pacific and Indian-ocean holdings, the Dutch
  Caribbean, Norway's Bouvet Island, Chile's Easter Island). The raw box is
  correct but useless for "frame this country"; the mainland is what is wanted.

Run from the repository root with the Natural Earth 1:10m data present:

    python3 scripts/generate_country_boxes.py
"""

from __future__ import annotations

from pathlib import Path

import fiona

SHAPEFILE = Path(
    "datasets/natural_earth_10m/ne_10m_admin_0_countries/ne_10m_admin_0_countries.shp"
)
OUTPUT = Path("src/hipparchus/application/country_boxes.py")

# Only these Natural Earth TYPE values are sovereign countries; the rest are
# dependencies, disputed areas and the like, which the menu does not list.
COUNTRY_TYPES = {"Sovereign country", "Country"}

# Curated mainland boxes for the countries whose raw bounds mislead. Keyed by
# Natural Earth's NAME field. See the module docstring for why each is here.
CURATED: dict[str, tuple[float, float, float, float]] = {
    "Russia": (19.6, 41.2, 180.0, 81.9),
    "United States of America": (-168.0, 18.9, -66.9, 71.4),
    "Fiji": (176.9, -19.3, 180.0, -16.0),
    "New Zealand": (166.3, -47.3, 178.6, -34.4),
    "Kiribati": (172.9, -3.5, 176.9, 2.1),
    "France": (-5.2, 41.3, 9.6, 51.1),
    "Netherlands": (3.3, 50.7, 7.2, 53.6),
    "Norway": (4.5, 57.9, 31.1, 71.2),
    "Chile": (-75.7, -56.0, -66.4, -17.5),
}

# Natural Earth files a handful of island nations under "Seven seas (open
# ocean)"; place them on the continent a reader would look under.
CONTINENT_FIX: dict[str, str] = {
    "Seychelles": "Africa",
    "Mauritius": "Africa",
    "Maldives": "Asia",
}


def _raw_bbox(geometry: dict) -> tuple[float, float, float, float]:
    xs: list[float] = []
    ys: list[float] = []

    def walk(node: object) -> None:
        if isinstance(node, (list, tuple)) and node and isinstance(node[0], (int, float)):
            xs.append(float(node[0]))
            ys.append(float(node[1]))
        elif isinstance(node, (list, tuple)):
            for child in node:
                walk(child)

    walk(geometry["coordinates"])
    return min(xs), min(ys), max(xs), max(ys)


# The smallest frame a place is allowed. Rounding a microstate — the Vatican,
# Monaco — to two decimals can collapse its box to a line; a country you cannot
# frame is worse than one framed a little loosely.
MIN_SPAN = 0.04


def _finalize(box: tuple[float, float, float, float]) -> tuple[float, float, float, float]:
    min_lon, min_lat, max_lon, max_lat = (round(value, 2) for value in box)
    if max_lon - min_lon < MIN_SPAN:
        centre = (min_lon + max_lon) / 2
        min_lon, max_lon = round(centre - MIN_SPAN / 2, 2), round(centre + MIN_SPAN / 2, 2)
    if max_lat - min_lat < MIN_SPAN:
        centre = (min_lat + max_lat) / 2
        min_lat, max_lat = round(centre - MIN_SPAN / 2, 2), round(centre + MIN_SPAN / 2, 2)
    return min_lon, min_lat, max_lon, max_lat


def _collect() -> list[tuple[str, str, float, float, float, float]]:
    rows: list[tuple[str, str, float, float, float, float]] = []
    with fiona.open(SHAPEFILE) as source:
        for record in source:
            props = record["properties"]
            if props.get("TYPE") not in COUNTRY_TYPES:
                continue
            name = props.get("NAME") or props.get("NAME_EN")
            if not name:
                continue
            continent = CONTINENT_FIX.get(name, props.get("CONTINENT") or "Other")
            box = _finalize(CURATED.get(name) or _raw_bbox(record["geometry"]))
            rows.append((name, continent, *box))
    rows.sort(key=lambda row: (row[1], row[0]))
    return rows


def _render(rows: list[tuple[str, str, float, float, float, float]]) -> str:
    lines = [
        '"""Country bounding boxes, grouped by continent.',
        "",
        "Generated by ``scripts/generate_country_boxes.py`` from Natural Earth 1:10m",
        "admin_0 countries (public domain). Do not edit by hand; re-run the generator.",
        "Antimeridian-spanning and distant-territory countries carry a curated mainland",
        "box rather than the raw geometry bounds.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "# (name, continent, min_lon, min_lat, max_lon, max_lat)",
        "COUNTRY_BOXES: tuple[tuple[str, str, float, float, float, float], ...] = (",
    ]
    for name, continent, x0, y0, x1, y1 in rows:
        lines.append(f"    ({name!r}, {continent!r}, {x0}, {y0}, {x1}, {y1}),")
    lines.append(")")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    if not SHAPEFILE.exists():
        raise SystemExit(
            f"Natural Earth 1:10m data not found at {SHAPEFILE}. "
            "Download it first (see the Natural Earth download in the app)."
        )
    rows = _collect()
    OUTPUT.write_text(_render(rows), encoding="utf-8")
    by_continent: dict[str, int] = {}
    for _, continent, *_rest in rows:
        by_continent[continent] = by_continent.get(continent, 0) + 1
    print(f"Wrote {len(rows)} countries to {OUTPUT}")
    for continent in sorted(by_continent):
        print(f"  {continent}: {by_continent[continent]}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
